-- SQLite schema for mapping CAD_Station JSON payloads.
-- Source class: CAD_Station in CAD_Library/SolidworksLibrary.

CREATE TABLE IF NOT EXISTS cad_station (
    station_id TEXT PRIMARY KEY,
    name TEXT,
    version TEXT,
    station_type INTEGER NOT NULL CHECK (station_type BETWEEN 0 AND 4),
    axial_location REAL NOT NULL DEFAULT 0,
    radial_location REAL NOT NULL DEFAULT 0,
    angular_location REAL NOT NULL DEFAULT 0,
    wing_location REAL NOT NULL DEFAULT 0,
    floor_location REAL NOT NULL DEFAULT 0,
    my_model_json TEXT,
    current_sketch_plane_json TEXT,
    sketch_planes_json TEXT NOT NULL DEFAULT '[]',
    source_json TEXT NOT NULL,
    created_utc TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_utc TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    CHECK (json_valid(source_json)),
    CHECK (my_model_json IS NULL OR json_valid(my_model_json)),
    CHECK (current_sketch_plane_json IS NULL OR json_valid(current_sketch_plane_json)),
    CHECK (json_valid(sketch_planes_json))
);

CREATE INDEX IF NOT EXISTS idx_cad_station_station_type ON cad_station(station_type);
CREATE INDEX IF NOT EXISTS idx_cad_station_name ON cad_station(name);

-- Example JSON upsert mapping.
-- Bind :station_json to the JSON generated by CAD_Station.ToJson().
/*
INSERT INTO cad_station (
    station_id,
    name,
    version,
    station_type,
    axial_location,
    radial_location,
    angular_location,
    wing_location,
    floor_location,
    my_model_json,
    current_sketch_plane_json,
    sketch_planes_json,
    source_json,
    updated_utc
)
VALUES (
    COALESCE(json_extract(:station_json, '$.ID'), lower(hex(randomblob(16)))),
    json_extract(:station_json, '$.Name'),
    json_extract(:station_json, '$.Version'),
    COALESCE(json_extract(:station_json, '$.MyType'), 0),
    COALESCE(json_extract(:station_json, '$.AxialLocation'), 0),
    COALESCE(json_extract(:station_json, '$.RadialLocation'), 0),
    COALESCE(json_extract(:station_json, '$.AngularLocation'), 0),
    COALESCE(json_extract(:station_json, '$.WingLocation'), 0),
    COALESCE(json_extract(:station_json, '$.FloorLocation'), 0),
    json_extract(:station_json, '$.MyModel'),
    json_extract(:station_json, '$.CurrentSketchPlane'),
    COALESCE(json_extract(:station_json, '$.MySketchPlanes'), '[]'),
    :station_json,
    strftime('%Y-%m-%dT%H:%M:%fZ','now')
)
ON CONFLICT(station_id) DO UPDATE SET
    name = excluded.name,
    version = excluded.version,
    station_type = excluded.station_type,
    axial_location = excluded.axial_location,
    radial_location = excluded.radial_location,
    angular_location = excluded.angular_location,
    wing_location = excluded.wing_location,
    floor_location = excluded.floor_location,
    my_model_json = excluded.my_model_json,
    current_sketch_plane_json = excluded.current_sketch_plane_json,
    sketch_planes_json = excluded.sketch_planes_json,
    source_json = excluded.source_json,
    updated_utc = excluded.updated_utc;
*/
